### ISSUE TITLE
Compatible firmware for the repeater board ver. 3b4 F4 

### ISSUE THREAD

**Issue by F4EWI** [JTA-STAR/J-STAR#1]
Currently I have firmware version 1.6.1 (MMDVM_HS-Dual_Hat) installed on the board (version developed for the WPSD Project). Is it compatible with J-Star distribution ?
If not, which firmware version should I use and where can I download it?

**Comment by bi7jta** [comment]
Upgrade MMDVM repeater board V3F4 to the new firmware ,and set 460800 BAUD, or 115200 BAUD
https://www.bi7jta.org/wiki/index.php?title=Main_Page#FM_Network_460800bps.28Connect_to_Allstarlink.29

![image](https://github.com/JTA-STAR/J-STAR/assets/22002824/fed0f504-09ad-436c-95c1-1c0d9dc95842)
