### ISSUE TITLE
package for Debian Desktop on Linux (virtual/real) PC?

### ISSUE THREAD

**Issue by jg1uaa** [JTA-STAR/J-STAR#18]
Desktop Pi-Star looks good idea and I think it can be applied to Debian Desktop on x86 virtual machine such as VirtualBox (maybe VMware) or real machine, with MMDVM-USB HAT.
How do you think about this idea?

**Comment by charugaa** [comment]
How to install J-STAR on a classic Debian x64 machine without VirtualBox.

**Comment by bi7jta** [comment]
> Desktop Pi-Star looks good idea and I think it can be applied to Debian Desktop on x86 virtual machine such as VirtualBox (maybe VMware) or real machine, with MMDVM-USB HAT. How do you think about this idea?

Hi, 
download from https://github.com/JTA-STAR/J-STAR/blob/main/README.md 
then  , click "update" sync the new version.

VMware, ESXi need you export from VisualBox yourself , I think not a hard work.

**Comment by bi7jta** [comment]
> > Desktop Pi-Star looks good idea and I think it can be applied to Debian Desktop on x86 virtual machine such as VirtualBox (maybe VMware) or real machine, with MMDVM-USB HAT. How do you think about this idea?
> 
> Hi, download from https://github.com/JTA-STAR/J-STAR/blob/main/README.md then , click "update" sync the new version.
> 
> VMware, ESXi need you export from VisualBox yourself , I think not a hard work.



> How to install J-STAR on a classic Debian x64 machine without VirtualBox.



> How to install J-STAR on a classic Debian x64 machine without VirtualBox.

Hi, 
download from https://github.com/JTA-STAR/J-STAR/blob/main/README.md 
then  , click "update" sync the new version.

No Debian x64 Physical machine plan, main purpose is Raspberry Pi 4B,5B ,2W. 
X86 VM is for J-STAR + FreeDMR server, RustDesk server.
